env:
  browser: true
  es6: true
  node: true
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "google"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  array-element-newline:
    - error
    - consistent
  object-curly-spacing:
    - 2
    - always
  semi:
    - error
    - never
  quote-props:
    - error
    - as-needed
  max-len:
    - error
    - code: 160
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  react/prop-types: "off"
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
  react/display-name: "off"
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: "all"
      args: "after-used"
      ignoreRestSiblings: false
  import/no-unresolved: "off"
  import/no-named-as-default-member: 0
  import/order:
    - error
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "parent"
        - "sibling"
        - "index"
      pathGroupsExcludedImportTypes:
        - "react"
      pathGroups:
        - pattern: "@emotion/react"
          group: "builtin"
          position: "before"
        - pattern: "react"
          group: "builtin"
          position: "before"
        - pattern: "/**"
          group: "internal"
          position: "after"
      alphabetize:
        order: "asc"
        caseInsensitive: true
settings:
  react:
    version: "detect"
  import/resolver:
    typescript:
overrides:
  - files:
      - "*.d.ts"
    rules:
      "@typescript-eslint/no-explicit-any": "off"
