name: publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:

  publish:
    name: publish
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm ci

      - run: |
          npm run test

      - run: |
          sudo apt update
          sudo apt install -y jq
          V1=$(cat package.json | jq .version | sed -e "s/\"//g" | sed -e "s/^/v/")
          V2=${GITHUB_REF#refs/tags/}
          test $V1 = $V2

      - run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
