name: release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Get dependencies
        run: |
          yarn install

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Check Version Consistency
        run: |
          sudo apt update
          sudo apt install -y jq
          V1=$(cat package.json | jq .version | sed -e "s/\"//g" | sed -e "s/^/v/")
          V2=${GITHUB_REF#refs/tags/}
          test $V1 = $V2

      - name: Publish
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
